### ISSUE TITLE
Could you provide the preprocessing code of diginetica data

### ISSUE THREAD

**Issue by xieck13** [The-Learning-Machines/SBR#1]
I am very interested in this article and tried to run the project, but I found that the current code could not preprocess the diginetica dataset.

Could you help me? Thanks!

**Comment by smj007** [comment]
Hi, thank you for your interest in our work. The preprocessing code provided in our repository is for Yoochoose 1/64 for Timestamp data which would improve the performance of the model but is not included in this work. 

The pre-processing code you're looking for, to convert Diginetica to the usable form, can be found [Here](https://github.com/kunwuz/DGTN/blob/master/preprocess/cikm16_perprocess.py)

**However, do note that we provide the data in the processed form, so you can directly use it for our model.**

**Comment by xieck13** [comment]
Thanks for your reply!
I used the test dataset in the project, and tried to re-emerge the experiment. However, I found the result about hit@20 is closed to 51.60, which was a gap with result in "paper with code". Do I need to adjust hyper-parameter? Could you share the setting of hyper-parameter?

ps: I found the score in validation dataset is closed to 56, but it seems that the data distribution in test datset is quite different from training dataset.
